name: platform_device_id_platform_interface
description: A common platform interface for the platform_device_id plugin.
homepage: https://github.com/BestBurning/platform_device_id/tree/master/platform_device_id_platform_interface
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

