name: platform_device_id
description: You can get device id from platform - linux/mac/windows/android/ios/web.
version: 1.0.1
homepage: https://github.com/BestBurning/platform_device_id

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  platform_device_id_platform_interface:
    git:
      url: https://github.com/ibrahimMahfuz/platform_device_id.git
      path: platform_device_id_platform_interface
      ref: test
  device_info: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.di1shuai.platform_device_id
        pluginClass: PlatformDeviceIdPlugin
      ios:
        pluginClass: PlatformDeviceIdPlugin

